#!/usr/bin/env python3

# Libraries
import json
import locale
import sys

def load_data(filename):
    """Loads the contents of filename as a JSON file"""
    with open(filename) as json_file:
        data = json.load(json_file)
    return data

def max_revenue(monthly_car_sales):
    """1. Calculate the car model with the most revenue"""
    # Variables
    max_revenue = {"revenue": 0}
    for car in monthly_car_sales:
        # Calculate the revenue generated by this model (price * total_sales)
		# (!) We need to convert the price from "$1234.56" to 1234.56
        car_price = locale.atof(car["price"].strip("$"))
        car_revenue = car_price * car["total_sales"]
        if car_revenue > max_revenue["revenue"]:
            car["revenue"] = car_revenue
            max_revenue = car

    summary = [
        "The {} generated the most revenue: ${}".format(
            max_revenue["car"], max_revenue["revenue"])
    ]
    return summary

def main():
    raw_data = load_data("car_sales.json")
    print(max_revenue(raw_data))

if __name__ == "__main__":
    main()